// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CertificatesColumns holds the columns for the "certificates" table.
	CertificatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "common_name", Type: field.TypeString},
		{Name: "serial_number", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"root_ca", "intermediate_ca", "server", "client"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"valid", "revoked", "expired"}, Default: "valid"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
		{Name: "key_type", Type: field.TypeString},
		{Name: "fingerprint", Type: field.TypeString},
		{Name: "cert_path", Type: field.TypeString},
		{Name: "key_path", Type: field.TypeString},
		{Name: "organization", Type: field.TypeString, Nullable: true},
		{Name: "country", Type: field.TypeString, Nullable: true},
		{Name: "dns_names", Type: field.TypeJSON, Nullable: true},
		{Name: "ip_addresses", Type: field.TypeJSON, Nullable: true},
		{Name: "is_ca", Type: field.TypeBool, Default: false},
		{Name: "certificate_children", Type: field.TypeInt, Nullable: true},
	}
	// CertificatesTable holds the schema information for the "certificates" table.
	CertificatesTable = &schema.Table{
		Name:       "certificates",
		Columns:    CertificatesColumns,
		PrimaryKey: []*schema.Column{CertificatesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "certificates_certificates_children",
				Columns:    []*schema.Column{CertificatesColumns[17]},
				RefColumns: []*schema.Column{CertificatesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CertificatesTable,
	}
)

func init() {
	CertificatesTable.ForeignKeys[0].RefTable = CertificatesTable
}
