// Code generated by ent, DO NOT EDIT.

package certificate

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the certificate type in the database.
	Label = "certificate"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCommonName holds the string denoting the common_name field in the database.
	FieldCommonName = "common_name"
	// FieldSerialNumber holds the string denoting the serial_number field in the database.
	FieldSerialNumber = "serial_number"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldRevokedAt holds the string denoting the revoked_at field in the database.
	FieldRevokedAt = "revoked_at"
	// FieldKeyType holds the string denoting the key_type field in the database.
	FieldKeyType = "key_type"
	// FieldFingerprint holds the string denoting the fingerprint field in the database.
	FieldFingerprint = "fingerprint"
	// FieldCertPath holds the string denoting the cert_path field in the database.
	FieldCertPath = "cert_path"
	// FieldKeyPath holds the string denoting the key_path field in the database.
	FieldKeyPath = "key_path"
	// FieldOrganization holds the string denoting the organization field in the database.
	FieldOrganization = "organization"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldDNSNames holds the string denoting the dns_names field in the database.
	FieldDNSNames = "dns_names"
	// FieldIPAddresses holds the string denoting the ip_addresses field in the database.
	FieldIPAddresses = "ip_addresses"
	// FieldIsCa holds the string denoting the is_ca field in the database.
	FieldIsCa = "is_ca"
	// EdgeIssuer holds the string denoting the issuer edge name in mutations.
	EdgeIssuer = "issuer"
	// EdgeChildren holds the string denoting the children edge name in mutations.
	EdgeChildren = "children"
	// Table holds the table name of the certificate in the database.
	Table = "certificates"
	// IssuerTable is the table that holds the issuer relation/edge.
	IssuerTable = "certificates"
	// IssuerColumn is the table column denoting the issuer relation/edge.
	IssuerColumn = "certificate_children"
	// ChildrenTable is the table that holds the children relation/edge.
	ChildrenTable = "certificates"
	// ChildrenColumn is the table column denoting the children relation/edge.
	ChildrenColumn = "certificate_children"
)

// Columns holds all SQL columns for certificate fields.
var Columns = []string{
	FieldID,
	FieldCommonName,
	FieldSerialNumber,
	FieldType,
	FieldStatus,
	FieldCreatedAt,
	FieldExpiresAt,
	FieldRevokedAt,
	FieldKeyType,
	FieldFingerprint,
	FieldCertPath,
	FieldKeyPath,
	FieldOrganization,
	FieldCountry,
	FieldDNSNames,
	FieldIPAddresses,
	FieldIsCa,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "certificates"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"certificate_children",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultIsCa holds the default value on creation for the "is_ca" field.
	DefaultIsCa bool
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeRootCa         Type = "root_ca"
	TypeIntermediateCa Type = "intermediate_ca"
	TypeServer         Type = "server"
	TypeClient         Type = "client"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeRootCa, TypeIntermediateCa, TypeServer, TypeClient:
		return nil
	default:
		return fmt.Errorf("certificate: invalid enum value for type field: %q", _type)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusValid is the default value of the Status enum.
const DefaultStatus = StatusValid

// Status values.
const (
	StatusValid   Status = "valid"
	StatusRevoked Status = "revoked"
	StatusExpired Status = "expired"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusValid, StatusRevoked, StatusExpired:
		return nil
	default:
		return fmt.Errorf("certificate: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Certificate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCommonName orders the results by the common_name field.
func ByCommonName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommonName, opts...).ToFunc()
}

// BySerialNumber orders the results by the serial_number field.
func BySerialNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSerialNumber, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByRevokedAt orders the results by the revoked_at field.
func ByRevokedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevokedAt, opts...).ToFunc()
}

// ByKeyType orders the results by the key_type field.
func ByKeyType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyType, opts...).ToFunc()
}

// ByFingerprint orders the results by the fingerprint field.
func ByFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFingerprint, opts...).ToFunc()
}

// ByCertPath orders the results by the cert_path field.
func ByCertPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCertPath, opts...).ToFunc()
}

// ByKeyPath orders the results by the key_path field.
func ByKeyPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyPath, opts...).ToFunc()
}

// ByOrganization orders the results by the organization field.
func ByOrganization(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganization, opts...).ToFunc()
}

// ByCountry orders the results by the country field.
func ByCountry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCountry, opts...).ToFunc()
}

// ByIsCa orders the results by the is_ca field.
func ByIsCa(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsCa, opts...).ToFunc()
}

// ByIssuerField orders the results by issuer field.
func ByIssuerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newIssuerStep(), sql.OrderByField(field, opts...))
	}
}

// ByChildrenCount orders the results by children count.
func ByChildrenCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChildrenStep(), opts...)
	}
}

// ByChildren orders the results by children terms.
func ByChildren(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChildrenStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newIssuerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, IssuerTable, IssuerColumn),
	)
}
func newChildrenStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChildrenTable, ChildrenColumn),
	)
}
