// Code generated by ent, DO NOT EDIT.

package certificate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/snowmerak/mtls/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldID, id))
}

// CommonName applies equality check predicate on the "common_name" field. It's identical to CommonNameEQ.
func CommonName(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldCommonName, v))
}

// SerialNumber applies equality check predicate on the "serial_number" field. It's identical to SerialNumberEQ.
func SerialNumber(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldSerialNumber, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldCreatedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldExpiresAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldRevokedAt, v))
}

// KeyType applies equality check predicate on the "key_type" field. It's identical to KeyTypeEQ.
func KeyType(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldKeyType, v))
}

// Fingerprint applies equality check predicate on the "fingerprint" field. It's identical to FingerprintEQ.
func Fingerprint(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldFingerprint, v))
}

// CertPath applies equality check predicate on the "cert_path" field. It's identical to CertPathEQ.
func CertPath(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldCertPath, v))
}

// KeyPath applies equality check predicate on the "key_path" field. It's identical to KeyPathEQ.
func KeyPath(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldKeyPath, v))
}

// Organization applies equality check predicate on the "organization" field. It's identical to OrganizationEQ.
func Organization(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldOrganization, v))
}

// Country applies equality check predicate on the "country" field. It's identical to CountryEQ.
func Country(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldCountry, v))
}

// IsCa applies equality check predicate on the "is_ca" field. It's identical to IsCaEQ.
func IsCa(v bool) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldIsCa, v))
}

// CommonNameEQ applies the EQ predicate on the "common_name" field.
func CommonNameEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldCommonName, v))
}

// CommonNameNEQ applies the NEQ predicate on the "common_name" field.
func CommonNameNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldCommonName, v))
}

// CommonNameIn applies the In predicate on the "common_name" field.
func CommonNameIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldCommonName, vs...))
}

// CommonNameNotIn applies the NotIn predicate on the "common_name" field.
func CommonNameNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldCommonName, vs...))
}

// CommonNameGT applies the GT predicate on the "common_name" field.
func CommonNameGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldCommonName, v))
}

// CommonNameGTE applies the GTE predicate on the "common_name" field.
func CommonNameGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldCommonName, v))
}

// CommonNameLT applies the LT predicate on the "common_name" field.
func CommonNameLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldCommonName, v))
}

// CommonNameLTE applies the LTE predicate on the "common_name" field.
func CommonNameLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldCommonName, v))
}

// CommonNameContains applies the Contains predicate on the "common_name" field.
func CommonNameContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldCommonName, v))
}

// CommonNameHasPrefix applies the HasPrefix predicate on the "common_name" field.
func CommonNameHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldCommonName, v))
}

// CommonNameHasSuffix applies the HasSuffix predicate on the "common_name" field.
func CommonNameHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldCommonName, v))
}

// CommonNameEqualFold applies the EqualFold predicate on the "common_name" field.
func CommonNameEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldCommonName, v))
}

// CommonNameContainsFold applies the ContainsFold predicate on the "common_name" field.
func CommonNameContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldCommonName, v))
}

// SerialNumberEQ applies the EQ predicate on the "serial_number" field.
func SerialNumberEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldSerialNumber, v))
}

// SerialNumberNEQ applies the NEQ predicate on the "serial_number" field.
func SerialNumberNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldSerialNumber, v))
}

// SerialNumberIn applies the In predicate on the "serial_number" field.
func SerialNumberIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldSerialNumber, vs...))
}

// SerialNumberNotIn applies the NotIn predicate on the "serial_number" field.
func SerialNumberNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldSerialNumber, vs...))
}

// SerialNumberGT applies the GT predicate on the "serial_number" field.
func SerialNumberGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldSerialNumber, v))
}

// SerialNumberGTE applies the GTE predicate on the "serial_number" field.
func SerialNumberGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldSerialNumber, v))
}

// SerialNumberLT applies the LT predicate on the "serial_number" field.
func SerialNumberLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldSerialNumber, v))
}

// SerialNumberLTE applies the LTE predicate on the "serial_number" field.
func SerialNumberLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldSerialNumber, v))
}

// SerialNumberContains applies the Contains predicate on the "serial_number" field.
func SerialNumberContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldSerialNumber, v))
}

// SerialNumberHasPrefix applies the HasPrefix predicate on the "serial_number" field.
func SerialNumberHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldSerialNumber, v))
}

// SerialNumberHasSuffix applies the HasSuffix predicate on the "serial_number" field.
func SerialNumberHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldSerialNumber, v))
}

// SerialNumberEqualFold applies the EqualFold predicate on the "serial_number" field.
func SerialNumberEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldSerialNumber, v))
}

// SerialNumberContainsFold applies the ContainsFold predicate on the "serial_number" field.
func SerialNumberContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldSerialNumber, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldType, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldStatus, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldCreatedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldExpiresAt, v))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldNotNull(FieldRevokedAt))
}

// KeyTypeEQ applies the EQ predicate on the "key_type" field.
func KeyTypeEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldKeyType, v))
}

// KeyTypeNEQ applies the NEQ predicate on the "key_type" field.
func KeyTypeNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldKeyType, v))
}

// KeyTypeIn applies the In predicate on the "key_type" field.
func KeyTypeIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldKeyType, vs...))
}

// KeyTypeNotIn applies the NotIn predicate on the "key_type" field.
func KeyTypeNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldKeyType, vs...))
}

// KeyTypeGT applies the GT predicate on the "key_type" field.
func KeyTypeGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldKeyType, v))
}

// KeyTypeGTE applies the GTE predicate on the "key_type" field.
func KeyTypeGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldKeyType, v))
}

// KeyTypeLT applies the LT predicate on the "key_type" field.
func KeyTypeLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldKeyType, v))
}

// KeyTypeLTE applies the LTE predicate on the "key_type" field.
func KeyTypeLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldKeyType, v))
}

// KeyTypeContains applies the Contains predicate on the "key_type" field.
func KeyTypeContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldKeyType, v))
}

// KeyTypeHasPrefix applies the HasPrefix predicate on the "key_type" field.
func KeyTypeHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldKeyType, v))
}

// KeyTypeHasSuffix applies the HasSuffix predicate on the "key_type" field.
func KeyTypeHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldKeyType, v))
}

// KeyTypeEqualFold applies the EqualFold predicate on the "key_type" field.
func KeyTypeEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldKeyType, v))
}

// KeyTypeContainsFold applies the ContainsFold predicate on the "key_type" field.
func KeyTypeContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldKeyType, v))
}

// FingerprintEQ applies the EQ predicate on the "fingerprint" field.
func FingerprintEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldFingerprint, v))
}

// FingerprintNEQ applies the NEQ predicate on the "fingerprint" field.
func FingerprintNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldFingerprint, v))
}

// FingerprintIn applies the In predicate on the "fingerprint" field.
func FingerprintIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldFingerprint, vs...))
}

// FingerprintNotIn applies the NotIn predicate on the "fingerprint" field.
func FingerprintNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldFingerprint, vs...))
}

// FingerprintGT applies the GT predicate on the "fingerprint" field.
func FingerprintGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldFingerprint, v))
}

// FingerprintGTE applies the GTE predicate on the "fingerprint" field.
func FingerprintGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldFingerprint, v))
}

// FingerprintLT applies the LT predicate on the "fingerprint" field.
func FingerprintLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldFingerprint, v))
}

// FingerprintLTE applies the LTE predicate on the "fingerprint" field.
func FingerprintLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldFingerprint, v))
}

// FingerprintContains applies the Contains predicate on the "fingerprint" field.
func FingerprintContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldFingerprint, v))
}

// FingerprintHasPrefix applies the HasPrefix predicate on the "fingerprint" field.
func FingerprintHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldFingerprint, v))
}

// FingerprintHasSuffix applies the HasSuffix predicate on the "fingerprint" field.
func FingerprintHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldFingerprint, v))
}

// FingerprintEqualFold applies the EqualFold predicate on the "fingerprint" field.
func FingerprintEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldFingerprint, v))
}

// FingerprintContainsFold applies the ContainsFold predicate on the "fingerprint" field.
func FingerprintContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldFingerprint, v))
}

// CertPathEQ applies the EQ predicate on the "cert_path" field.
func CertPathEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldCertPath, v))
}

// CertPathNEQ applies the NEQ predicate on the "cert_path" field.
func CertPathNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldCertPath, v))
}

// CertPathIn applies the In predicate on the "cert_path" field.
func CertPathIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldCertPath, vs...))
}

// CertPathNotIn applies the NotIn predicate on the "cert_path" field.
func CertPathNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldCertPath, vs...))
}

// CertPathGT applies the GT predicate on the "cert_path" field.
func CertPathGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldCertPath, v))
}

// CertPathGTE applies the GTE predicate on the "cert_path" field.
func CertPathGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldCertPath, v))
}

// CertPathLT applies the LT predicate on the "cert_path" field.
func CertPathLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldCertPath, v))
}

// CertPathLTE applies the LTE predicate on the "cert_path" field.
func CertPathLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldCertPath, v))
}

// CertPathContains applies the Contains predicate on the "cert_path" field.
func CertPathContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldCertPath, v))
}

// CertPathHasPrefix applies the HasPrefix predicate on the "cert_path" field.
func CertPathHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldCertPath, v))
}

// CertPathHasSuffix applies the HasSuffix predicate on the "cert_path" field.
func CertPathHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldCertPath, v))
}

// CertPathEqualFold applies the EqualFold predicate on the "cert_path" field.
func CertPathEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldCertPath, v))
}

// CertPathContainsFold applies the ContainsFold predicate on the "cert_path" field.
func CertPathContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldCertPath, v))
}

// KeyPathEQ applies the EQ predicate on the "key_path" field.
func KeyPathEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldKeyPath, v))
}

// KeyPathNEQ applies the NEQ predicate on the "key_path" field.
func KeyPathNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldKeyPath, v))
}

// KeyPathIn applies the In predicate on the "key_path" field.
func KeyPathIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldKeyPath, vs...))
}

// KeyPathNotIn applies the NotIn predicate on the "key_path" field.
func KeyPathNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldKeyPath, vs...))
}

// KeyPathGT applies the GT predicate on the "key_path" field.
func KeyPathGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldKeyPath, v))
}

// KeyPathGTE applies the GTE predicate on the "key_path" field.
func KeyPathGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldKeyPath, v))
}

// KeyPathLT applies the LT predicate on the "key_path" field.
func KeyPathLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldKeyPath, v))
}

// KeyPathLTE applies the LTE predicate on the "key_path" field.
func KeyPathLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldKeyPath, v))
}

// KeyPathContains applies the Contains predicate on the "key_path" field.
func KeyPathContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldKeyPath, v))
}

// KeyPathHasPrefix applies the HasPrefix predicate on the "key_path" field.
func KeyPathHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldKeyPath, v))
}

// KeyPathHasSuffix applies the HasSuffix predicate on the "key_path" field.
func KeyPathHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldKeyPath, v))
}

// KeyPathEqualFold applies the EqualFold predicate on the "key_path" field.
func KeyPathEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldKeyPath, v))
}

// KeyPathContainsFold applies the ContainsFold predicate on the "key_path" field.
func KeyPathContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldKeyPath, v))
}

// OrganizationEQ applies the EQ predicate on the "organization" field.
func OrganizationEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldOrganization, v))
}

// OrganizationNEQ applies the NEQ predicate on the "organization" field.
func OrganizationNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldOrganization, v))
}

// OrganizationIn applies the In predicate on the "organization" field.
func OrganizationIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldOrganization, vs...))
}

// OrganizationNotIn applies the NotIn predicate on the "organization" field.
func OrganizationNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldOrganization, vs...))
}

// OrganizationGT applies the GT predicate on the "organization" field.
func OrganizationGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldOrganization, v))
}

// OrganizationGTE applies the GTE predicate on the "organization" field.
func OrganizationGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldOrganization, v))
}

// OrganizationLT applies the LT predicate on the "organization" field.
func OrganizationLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldOrganization, v))
}

// OrganizationLTE applies the LTE predicate on the "organization" field.
func OrganizationLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldOrganization, v))
}

// OrganizationContains applies the Contains predicate on the "organization" field.
func OrganizationContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldOrganization, v))
}

// OrganizationHasPrefix applies the HasPrefix predicate on the "organization" field.
func OrganizationHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldOrganization, v))
}

// OrganizationHasSuffix applies the HasSuffix predicate on the "organization" field.
func OrganizationHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldOrganization, v))
}

// OrganizationIsNil applies the IsNil predicate on the "organization" field.
func OrganizationIsNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldIsNull(FieldOrganization))
}

// OrganizationNotNil applies the NotNil predicate on the "organization" field.
func OrganizationNotNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldNotNull(FieldOrganization))
}

// OrganizationEqualFold applies the EqualFold predicate on the "organization" field.
func OrganizationEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldOrganization, v))
}

// OrganizationContainsFold applies the ContainsFold predicate on the "organization" field.
func OrganizationContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldOrganization, v))
}

// CountryEQ applies the EQ predicate on the "country" field.
func CountryEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldCountry, v))
}

// CountryNEQ applies the NEQ predicate on the "country" field.
func CountryNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldCountry, v))
}

// CountryIn applies the In predicate on the "country" field.
func CountryIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldCountry, vs...))
}

// CountryNotIn applies the NotIn predicate on the "country" field.
func CountryNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldCountry, vs...))
}

// CountryGT applies the GT predicate on the "country" field.
func CountryGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldCountry, v))
}

// CountryGTE applies the GTE predicate on the "country" field.
func CountryGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldCountry, v))
}

// CountryLT applies the LT predicate on the "country" field.
func CountryLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldCountry, v))
}

// CountryLTE applies the LTE predicate on the "country" field.
func CountryLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldCountry, v))
}

// CountryContains applies the Contains predicate on the "country" field.
func CountryContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldCountry, v))
}

// CountryHasPrefix applies the HasPrefix predicate on the "country" field.
func CountryHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldCountry, v))
}

// CountryHasSuffix applies the HasSuffix predicate on the "country" field.
func CountryHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldCountry, v))
}

// CountryIsNil applies the IsNil predicate on the "country" field.
func CountryIsNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldIsNull(FieldCountry))
}

// CountryNotNil applies the NotNil predicate on the "country" field.
func CountryNotNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldNotNull(FieldCountry))
}

// CountryEqualFold applies the EqualFold predicate on the "country" field.
func CountryEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldCountry, v))
}

// CountryContainsFold applies the ContainsFold predicate on the "country" field.
func CountryContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldCountry, v))
}

// DNSNamesIsNil applies the IsNil predicate on the "dns_names" field.
func DNSNamesIsNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldIsNull(FieldDNSNames))
}

// DNSNamesNotNil applies the NotNil predicate on the "dns_names" field.
func DNSNamesNotNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldNotNull(FieldDNSNames))
}

// IPAddressesIsNil applies the IsNil predicate on the "ip_addresses" field.
func IPAddressesIsNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldIsNull(FieldIPAddresses))
}

// IPAddressesNotNil applies the NotNil predicate on the "ip_addresses" field.
func IPAddressesNotNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldNotNull(FieldIPAddresses))
}

// IsCaEQ applies the EQ predicate on the "is_ca" field.
func IsCaEQ(v bool) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldIsCa, v))
}

// IsCaNEQ applies the NEQ predicate on the "is_ca" field.
func IsCaNEQ(v bool) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldIsCa, v))
}

// HasIssuer applies the HasEdge predicate on the "issuer" edge.
func HasIssuer() predicate.Certificate {
	return predicate.Certificate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, IssuerTable, IssuerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIssuerWith applies the HasEdge predicate on the "issuer" edge with a given conditions (other predicates).
func HasIssuerWith(preds ...predicate.Certificate) predicate.Certificate {
	return predicate.Certificate(func(s *sql.Selector) {
		step := newIssuerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChildren applies the HasEdge predicate on the "children" edge.
func HasChildren() predicate.Certificate {
	return predicate.Certificate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ChildrenTable, ChildrenColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChildrenWith applies the HasEdge predicate on the "children" edge with a given conditions (other predicates).
func HasChildrenWith(preds ...predicate.Certificate) predicate.Certificate {
	return predicate.Certificate(func(s *sql.Selector) {
		step := newChildrenStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Certificate) predicate.Certificate {
	return predicate.Certificate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Certificate) predicate.Certificate {
	return predicate.Certificate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Certificate) predicate.Certificate {
	return predicate.Certificate(sql.NotPredicates(p))
}
