// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/snowmerak/mtls/ent/certificate"
	"github.com/snowmerak/mtls/ent/predicate"
)

// CertificateUpdate is the builder for updating Certificate entities.
type CertificateUpdate struct {
	config
	hooks    []Hook
	mutation *CertificateMutation
}

// Where appends a list predicates to the CertificateUpdate builder.
func (_u *CertificateUpdate) Where(ps ...predicate.Certificate) *CertificateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCommonName sets the "common_name" field.
func (_u *CertificateUpdate) SetCommonName(v string) *CertificateUpdate {
	_u.mutation.SetCommonName(v)
	return _u
}

// SetNillableCommonName sets the "common_name" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableCommonName(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetCommonName(*v)
	}
	return _u
}

// SetSerialNumber sets the "serial_number" field.
func (_u *CertificateUpdate) SetSerialNumber(v string) *CertificateUpdate {
	_u.mutation.SetSerialNumber(v)
	return _u
}

// SetNillableSerialNumber sets the "serial_number" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableSerialNumber(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetSerialNumber(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *CertificateUpdate) SetType(v certificate.Type) *CertificateUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableType(v *certificate.Type) *CertificateUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CertificateUpdate) SetStatus(v certificate.Status) *CertificateUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableStatus(v *certificate.Status) *CertificateUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CertificateUpdate) SetCreatedAt(v time.Time) *CertificateUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableCreatedAt(v *time.Time) *CertificateUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CertificateUpdate) SetExpiresAt(v time.Time) *CertificateUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableExpiresAt(v *time.Time) *CertificateUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *CertificateUpdate) SetRevokedAt(v time.Time) *CertificateUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableRevokedAt(v *time.Time) *CertificateUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *CertificateUpdate) ClearRevokedAt() *CertificateUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetKeyType sets the "key_type" field.
func (_u *CertificateUpdate) SetKeyType(v string) *CertificateUpdate {
	_u.mutation.SetKeyType(v)
	return _u
}

// SetNillableKeyType sets the "key_type" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableKeyType(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetKeyType(*v)
	}
	return _u
}

// SetFingerprint sets the "fingerprint" field.
func (_u *CertificateUpdate) SetFingerprint(v string) *CertificateUpdate {
	_u.mutation.SetFingerprint(v)
	return _u
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableFingerprint(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetFingerprint(*v)
	}
	return _u
}

// SetCertPath sets the "cert_path" field.
func (_u *CertificateUpdate) SetCertPath(v string) *CertificateUpdate {
	_u.mutation.SetCertPath(v)
	return _u
}

// SetNillableCertPath sets the "cert_path" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableCertPath(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetCertPath(*v)
	}
	return _u
}

// SetKeyPath sets the "key_path" field.
func (_u *CertificateUpdate) SetKeyPath(v string) *CertificateUpdate {
	_u.mutation.SetKeyPath(v)
	return _u
}

// SetNillableKeyPath sets the "key_path" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableKeyPath(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetKeyPath(*v)
	}
	return _u
}

// SetOrganization sets the "organization" field.
func (_u *CertificateUpdate) SetOrganization(v string) *CertificateUpdate {
	_u.mutation.SetOrganization(v)
	return _u
}

// SetNillableOrganization sets the "organization" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableOrganization(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetOrganization(*v)
	}
	return _u
}

// ClearOrganization clears the value of the "organization" field.
func (_u *CertificateUpdate) ClearOrganization() *CertificateUpdate {
	_u.mutation.ClearOrganization()
	return _u
}

// SetCountry sets the "country" field.
func (_u *CertificateUpdate) SetCountry(v string) *CertificateUpdate {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableCountry(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// ClearCountry clears the value of the "country" field.
func (_u *CertificateUpdate) ClearCountry() *CertificateUpdate {
	_u.mutation.ClearCountry()
	return _u
}

// SetDNSNames sets the "dns_names" field.
func (_u *CertificateUpdate) SetDNSNames(v []string) *CertificateUpdate {
	_u.mutation.SetDNSNames(v)
	return _u
}

// AppendDNSNames appends value to the "dns_names" field.
func (_u *CertificateUpdate) AppendDNSNames(v []string) *CertificateUpdate {
	_u.mutation.AppendDNSNames(v)
	return _u
}

// ClearDNSNames clears the value of the "dns_names" field.
func (_u *CertificateUpdate) ClearDNSNames() *CertificateUpdate {
	_u.mutation.ClearDNSNames()
	return _u
}

// SetIPAddresses sets the "ip_addresses" field.
func (_u *CertificateUpdate) SetIPAddresses(v []string) *CertificateUpdate {
	_u.mutation.SetIPAddresses(v)
	return _u
}

// AppendIPAddresses appends value to the "ip_addresses" field.
func (_u *CertificateUpdate) AppendIPAddresses(v []string) *CertificateUpdate {
	_u.mutation.AppendIPAddresses(v)
	return _u
}

// ClearIPAddresses clears the value of the "ip_addresses" field.
func (_u *CertificateUpdate) ClearIPAddresses() *CertificateUpdate {
	_u.mutation.ClearIPAddresses()
	return _u
}

// SetIsCa sets the "is_ca" field.
func (_u *CertificateUpdate) SetIsCa(v bool) *CertificateUpdate {
	_u.mutation.SetIsCa(v)
	return _u
}

// SetNillableIsCa sets the "is_ca" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableIsCa(v *bool) *CertificateUpdate {
	if v != nil {
		_u.SetIsCa(*v)
	}
	return _u
}

// SetIssuerID sets the "issuer" edge to the Certificate entity by ID.
func (_u *CertificateUpdate) SetIssuerID(id int) *CertificateUpdate {
	_u.mutation.SetIssuerID(id)
	return _u
}

// SetNillableIssuerID sets the "issuer" edge to the Certificate entity by ID if the given value is not nil.
func (_u *CertificateUpdate) SetNillableIssuerID(id *int) *CertificateUpdate {
	if id != nil {
		_u = _u.SetIssuerID(*id)
	}
	return _u
}

// SetIssuer sets the "issuer" edge to the Certificate entity.
func (_u *CertificateUpdate) SetIssuer(v *Certificate) *CertificateUpdate {
	return _u.SetIssuerID(v.ID)
}

// AddChildIDs adds the "children" edge to the Certificate entity by IDs.
func (_u *CertificateUpdate) AddChildIDs(ids ...int) *CertificateUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Certificate entity.
func (_u *CertificateUpdate) AddChildren(v ...*Certificate) *CertificateUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// Mutation returns the CertificateMutation object of the builder.
func (_u *CertificateUpdate) Mutation() *CertificateMutation {
	return _u.mutation
}

// ClearIssuer clears the "issuer" edge to the Certificate entity.
func (_u *CertificateUpdate) ClearIssuer() *CertificateUpdate {
	_u.mutation.ClearIssuer()
	return _u
}

// ClearChildren clears all "children" edges to the Certificate entity.
func (_u *CertificateUpdate) ClearChildren() *CertificateUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Certificate entities by IDs.
func (_u *CertificateUpdate) RemoveChildIDs(ids ...int) *CertificateUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Certificate entities.
func (_u *CertificateUpdate) RemoveChildren(v ...*Certificate) *CertificateUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CertificateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CertificateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CertificateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CertificateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CertificateUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := certificate.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Certificate.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := certificate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Certificate.status": %w`, err)}
		}
	}
	return nil
}

func (_u *CertificateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(certificate.Table, certificate.Columns, sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CommonName(); ok {
		_spec.SetField(certificate.FieldCommonName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SerialNumber(); ok {
		_spec.SetField(certificate.FieldSerialNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(certificate.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(certificate.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(certificate.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(certificate.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(certificate.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(certificate.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.KeyType(); ok {
		_spec.SetField(certificate.FieldKeyType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Fingerprint(); ok {
		_spec.SetField(certificate.FieldFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.CertPath(); ok {
		_spec.SetField(certificate.FieldCertPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyPath(); ok {
		_spec.SetField(certificate.FieldKeyPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Organization(); ok {
		_spec.SetField(certificate.FieldOrganization, field.TypeString, value)
	}
	if _u.mutation.OrganizationCleared() {
		_spec.ClearField(certificate.FieldOrganization, field.TypeString)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(certificate.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.CountryCleared() {
		_spec.ClearField(certificate.FieldCountry, field.TypeString)
	}
	if value, ok := _u.mutation.DNSNames(); ok {
		_spec.SetField(certificate.FieldDNSNames, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDNSNames(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, certificate.FieldDNSNames, value)
		})
	}
	if _u.mutation.DNSNamesCleared() {
		_spec.ClearField(certificate.FieldDNSNames, field.TypeJSON)
	}
	if value, ok := _u.mutation.IPAddresses(); ok {
		_spec.SetField(certificate.FieldIPAddresses, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedIPAddresses(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, certificate.FieldIPAddresses, value)
		})
	}
	if _u.mutation.IPAddressesCleared() {
		_spec.ClearField(certificate.FieldIPAddresses, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsCa(); ok {
		_spec.SetField(certificate.FieldIsCa, field.TypeBool, value)
	}
	if _u.mutation.IssuerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   certificate.IssuerTable,
			Columns: []string{certificate.IssuerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IssuerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   certificate.IssuerTable,
			Columns: []string{certificate.IssuerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   certificate.ChildrenTable,
			Columns: []string{certificate.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   certificate.ChildrenTable,
			Columns: []string{certificate.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   certificate.ChildrenTable,
			Columns: []string{certificate.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{certificate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CertificateUpdateOne is the builder for updating a single Certificate entity.
type CertificateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CertificateMutation
}

// SetCommonName sets the "common_name" field.
func (_u *CertificateUpdateOne) SetCommonName(v string) *CertificateUpdateOne {
	_u.mutation.SetCommonName(v)
	return _u
}

// SetNillableCommonName sets the "common_name" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableCommonName(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetCommonName(*v)
	}
	return _u
}

// SetSerialNumber sets the "serial_number" field.
func (_u *CertificateUpdateOne) SetSerialNumber(v string) *CertificateUpdateOne {
	_u.mutation.SetSerialNumber(v)
	return _u
}

// SetNillableSerialNumber sets the "serial_number" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableSerialNumber(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetSerialNumber(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *CertificateUpdateOne) SetType(v certificate.Type) *CertificateUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableType(v *certificate.Type) *CertificateUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CertificateUpdateOne) SetStatus(v certificate.Status) *CertificateUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableStatus(v *certificate.Status) *CertificateUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CertificateUpdateOne) SetCreatedAt(v time.Time) *CertificateUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableCreatedAt(v *time.Time) *CertificateUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CertificateUpdateOne) SetExpiresAt(v time.Time) *CertificateUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableExpiresAt(v *time.Time) *CertificateUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *CertificateUpdateOne) SetRevokedAt(v time.Time) *CertificateUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableRevokedAt(v *time.Time) *CertificateUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *CertificateUpdateOne) ClearRevokedAt() *CertificateUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetKeyType sets the "key_type" field.
func (_u *CertificateUpdateOne) SetKeyType(v string) *CertificateUpdateOne {
	_u.mutation.SetKeyType(v)
	return _u
}

// SetNillableKeyType sets the "key_type" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableKeyType(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetKeyType(*v)
	}
	return _u
}

// SetFingerprint sets the "fingerprint" field.
func (_u *CertificateUpdateOne) SetFingerprint(v string) *CertificateUpdateOne {
	_u.mutation.SetFingerprint(v)
	return _u
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableFingerprint(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetFingerprint(*v)
	}
	return _u
}

// SetCertPath sets the "cert_path" field.
func (_u *CertificateUpdateOne) SetCertPath(v string) *CertificateUpdateOne {
	_u.mutation.SetCertPath(v)
	return _u
}

// SetNillableCertPath sets the "cert_path" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableCertPath(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetCertPath(*v)
	}
	return _u
}

// SetKeyPath sets the "key_path" field.
func (_u *CertificateUpdateOne) SetKeyPath(v string) *CertificateUpdateOne {
	_u.mutation.SetKeyPath(v)
	return _u
}

// SetNillableKeyPath sets the "key_path" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableKeyPath(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetKeyPath(*v)
	}
	return _u
}

// SetOrganization sets the "organization" field.
func (_u *CertificateUpdateOne) SetOrganization(v string) *CertificateUpdateOne {
	_u.mutation.SetOrganization(v)
	return _u
}

// SetNillableOrganization sets the "organization" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableOrganization(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetOrganization(*v)
	}
	return _u
}

// ClearOrganization clears the value of the "organization" field.
func (_u *CertificateUpdateOne) ClearOrganization() *CertificateUpdateOne {
	_u.mutation.ClearOrganization()
	return _u
}

// SetCountry sets the "country" field.
func (_u *CertificateUpdateOne) SetCountry(v string) *CertificateUpdateOne {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableCountry(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// ClearCountry clears the value of the "country" field.
func (_u *CertificateUpdateOne) ClearCountry() *CertificateUpdateOne {
	_u.mutation.ClearCountry()
	return _u
}

// SetDNSNames sets the "dns_names" field.
func (_u *CertificateUpdateOne) SetDNSNames(v []string) *CertificateUpdateOne {
	_u.mutation.SetDNSNames(v)
	return _u
}

// AppendDNSNames appends value to the "dns_names" field.
func (_u *CertificateUpdateOne) AppendDNSNames(v []string) *CertificateUpdateOne {
	_u.mutation.AppendDNSNames(v)
	return _u
}

// ClearDNSNames clears the value of the "dns_names" field.
func (_u *CertificateUpdateOne) ClearDNSNames() *CertificateUpdateOne {
	_u.mutation.ClearDNSNames()
	return _u
}

// SetIPAddresses sets the "ip_addresses" field.
func (_u *CertificateUpdateOne) SetIPAddresses(v []string) *CertificateUpdateOne {
	_u.mutation.SetIPAddresses(v)
	return _u
}

// AppendIPAddresses appends value to the "ip_addresses" field.
func (_u *CertificateUpdateOne) AppendIPAddresses(v []string) *CertificateUpdateOne {
	_u.mutation.AppendIPAddresses(v)
	return _u
}

// ClearIPAddresses clears the value of the "ip_addresses" field.
func (_u *CertificateUpdateOne) ClearIPAddresses() *CertificateUpdateOne {
	_u.mutation.ClearIPAddresses()
	return _u
}

// SetIsCa sets the "is_ca" field.
func (_u *CertificateUpdateOne) SetIsCa(v bool) *CertificateUpdateOne {
	_u.mutation.SetIsCa(v)
	return _u
}

// SetNillableIsCa sets the "is_ca" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableIsCa(v *bool) *CertificateUpdateOne {
	if v != nil {
		_u.SetIsCa(*v)
	}
	return _u
}

// SetIssuerID sets the "issuer" edge to the Certificate entity by ID.
func (_u *CertificateUpdateOne) SetIssuerID(id int) *CertificateUpdateOne {
	_u.mutation.SetIssuerID(id)
	return _u
}

// SetNillableIssuerID sets the "issuer" edge to the Certificate entity by ID if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableIssuerID(id *int) *CertificateUpdateOne {
	if id != nil {
		_u = _u.SetIssuerID(*id)
	}
	return _u
}

// SetIssuer sets the "issuer" edge to the Certificate entity.
func (_u *CertificateUpdateOne) SetIssuer(v *Certificate) *CertificateUpdateOne {
	return _u.SetIssuerID(v.ID)
}

// AddChildIDs adds the "children" edge to the Certificate entity by IDs.
func (_u *CertificateUpdateOne) AddChildIDs(ids ...int) *CertificateUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Certificate entity.
func (_u *CertificateUpdateOne) AddChildren(v ...*Certificate) *CertificateUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// Mutation returns the CertificateMutation object of the builder.
func (_u *CertificateUpdateOne) Mutation() *CertificateMutation {
	return _u.mutation
}

// ClearIssuer clears the "issuer" edge to the Certificate entity.
func (_u *CertificateUpdateOne) ClearIssuer() *CertificateUpdateOne {
	_u.mutation.ClearIssuer()
	return _u
}

// ClearChildren clears all "children" edges to the Certificate entity.
func (_u *CertificateUpdateOne) ClearChildren() *CertificateUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Certificate entities by IDs.
func (_u *CertificateUpdateOne) RemoveChildIDs(ids ...int) *CertificateUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Certificate entities.
func (_u *CertificateUpdateOne) RemoveChildren(v ...*Certificate) *CertificateUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// Where appends a list predicates to the CertificateUpdate builder.
func (_u *CertificateUpdateOne) Where(ps ...predicate.Certificate) *CertificateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CertificateUpdateOne) Select(field string, fields ...string) *CertificateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Certificate entity.
func (_u *CertificateUpdateOne) Save(ctx context.Context) (*Certificate, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CertificateUpdateOne) SaveX(ctx context.Context) *Certificate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CertificateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CertificateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CertificateUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := certificate.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Certificate.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := certificate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Certificate.status": %w`, err)}
		}
	}
	return nil
}

func (_u *CertificateUpdateOne) sqlSave(ctx context.Context) (_node *Certificate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(certificate.Table, certificate.Columns, sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Certificate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, certificate.FieldID)
		for _, f := range fields {
			if !certificate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != certificate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CommonName(); ok {
		_spec.SetField(certificate.FieldCommonName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SerialNumber(); ok {
		_spec.SetField(certificate.FieldSerialNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(certificate.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(certificate.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(certificate.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(certificate.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(certificate.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(certificate.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.KeyType(); ok {
		_spec.SetField(certificate.FieldKeyType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Fingerprint(); ok {
		_spec.SetField(certificate.FieldFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.CertPath(); ok {
		_spec.SetField(certificate.FieldCertPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyPath(); ok {
		_spec.SetField(certificate.FieldKeyPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Organization(); ok {
		_spec.SetField(certificate.FieldOrganization, field.TypeString, value)
	}
	if _u.mutation.OrganizationCleared() {
		_spec.ClearField(certificate.FieldOrganization, field.TypeString)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(certificate.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.CountryCleared() {
		_spec.ClearField(certificate.FieldCountry, field.TypeString)
	}
	if value, ok := _u.mutation.DNSNames(); ok {
		_spec.SetField(certificate.FieldDNSNames, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDNSNames(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, certificate.FieldDNSNames, value)
		})
	}
	if _u.mutation.DNSNamesCleared() {
		_spec.ClearField(certificate.FieldDNSNames, field.TypeJSON)
	}
	if value, ok := _u.mutation.IPAddresses(); ok {
		_spec.SetField(certificate.FieldIPAddresses, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedIPAddresses(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, certificate.FieldIPAddresses, value)
		})
	}
	if _u.mutation.IPAddressesCleared() {
		_spec.ClearField(certificate.FieldIPAddresses, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsCa(); ok {
		_spec.SetField(certificate.FieldIsCa, field.TypeBool, value)
	}
	if _u.mutation.IssuerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   certificate.IssuerTable,
			Columns: []string{certificate.IssuerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IssuerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   certificate.IssuerTable,
			Columns: []string{certificate.IssuerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   certificate.ChildrenTable,
			Columns: []string{certificate.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   certificate.ChildrenTable,
			Columns: []string{certificate.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   certificate.ChildrenTable,
			Columns: []string{certificate.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Certificate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{certificate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
