// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/snowmerak/mtls/ent/certificate"
)

// Certificate is the model entity for the Certificate schema.
type Certificate struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CommonName holds the value of the "common_name" field.
	CommonName string `json:"common_name,omitempty"`
	// SerialNumber holds the value of the "serial_number" field.
	SerialNumber string `json:"serial_number,omitempty"`
	// Type holds the value of the "type" field.
	Type certificate.Type `json:"type,omitempty"`
	// Status holds the value of the "status" field.
	Status certificate.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// KeyType holds the value of the "key_type" field.
	KeyType string `json:"key_type,omitempty"`
	// Fingerprint holds the value of the "fingerprint" field.
	Fingerprint string `json:"fingerprint,omitempty"`
	// CertPath holds the value of the "cert_path" field.
	CertPath string `json:"cert_path,omitempty"`
	// KeyPath holds the value of the "key_path" field.
	KeyPath string `json:"key_path,omitempty"`
	// Organization holds the value of the "organization" field.
	Organization string `json:"organization,omitempty"`
	// Country holds the value of the "country" field.
	Country string `json:"country,omitempty"`
	// DNSNames holds the value of the "dns_names" field.
	DNSNames []string `json:"dns_names,omitempty"`
	// IPAddresses holds the value of the "ip_addresses" field.
	IPAddresses []string `json:"ip_addresses,omitempty"`
	// IsCa holds the value of the "is_ca" field.
	IsCa bool `json:"is_ca,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CertificateQuery when eager-loading is set.
	Edges                CertificateEdges `json:"edges"`
	certificate_children *int
	selectValues         sql.SelectValues
}

// CertificateEdges holds the relations/edges for other nodes in the graph.
type CertificateEdges struct {
	// Issuer holds the value of the issuer edge.
	Issuer *Certificate `json:"issuer,omitempty"`
	// Children holds the value of the children edge.
	Children []*Certificate `json:"children,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// IssuerOrErr returns the Issuer value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CertificateEdges) IssuerOrErr() (*Certificate, error) {
	if e.Issuer != nil {
		return e.Issuer, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: certificate.Label}
	}
	return nil, &NotLoadedError{edge: "issuer"}
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e CertificateEdges) ChildrenOrErr() ([]*Certificate, error) {
	if e.loadedTypes[1] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Certificate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case certificate.FieldDNSNames, certificate.FieldIPAddresses:
			values[i] = new([]byte)
		case certificate.FieldIsCa:
			values[i] = new(sql.NullBool)
		case certificate.FieldID:
			values[i] = new(sql.NullInt64)
		case certificate.FieldCommonName, certificate.FieldSerialNumber, certificate.FieldType, certificate.FieldStatus, certificate.FieldKeyType, certificate.FieldFingerprint, certificate.FieldCertPath, certificate.FieldKeyPath, certificate.FieldOrganization, certificate.FieldCountry:
			values[i] = new(sql.NullString)
		case certificate.FieldCreatedAt, certificate.FieldExpiresAt, certificate.FieldRevokedAt:
			values[i] = new(sql.NullTime)
		case certificate.ForeignKeys[0]: // certificate_children
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Certificate fields.
func (_m *Certificate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case certificate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case certificate.FieldCommonName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field common_name", values[i])
			} else if value.Valid {
				_m.CommonName = value.String
			}
		case certificate.FieldSerialNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field serial_number", values[i])
			} else if value.Valid {
				_m.SerialNumber = value.String
			}
		case certificate.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = certificate.Type(value.String)
			}
		case certificate.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = certificate.Status(value.String)
			}
		case certificate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case certificate.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case certificate.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		case certificate.FieldKeyType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_type", values[i])
			} else if value.Valid {
				_m.KeyType = value.String
			}
		case certificate.FieldFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fingerprint", values[i])
			} else if value.Valid {
				_m.Fingerprint = value.String
			}
		case certificate.FieldCertPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cert_path", values[i])
			} else if value.Valid {
				_m.CertPath = value.String
			}
		case certificate.FieldKeyPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_path", values[i])
			} else if value.Valid {
				_m.KeyPath = value.String
			}
		case certificate.FieldOrganization:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field organization", values[i])
			} else if value.Valid {
				_m.Organization = value.String
			}
		case certificate.FieldCountry:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field country", values[i])
			} else if value.Valid {
				_m.Country = value.String
			}
		case certificate.FieldDNSNames:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field dns_names", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.DNSNames); err != nil {
					return fmt.Errorf("unmarshal field dns_names: %w", err)
				}
			}
		case certificate.FieldIPAddresses:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field ip_addresses", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.IPAddresses); err != nil {
					return fmt.Errorf("unmarshal field ip_addresses: %w", err)
				}
			}
		case certificate.FieldIsCa:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_ca", values[i])
			} else if value.Valid {
				_m.IsCa = value.Bool
			}
		case certificate.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field certificate_children", value)
			} else if value.Valid {
				_m.certificate_children = new(int)
				*_m.certificate_children = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Certificate.
// This includes values selected through modifiers, order, etc.
func (_m *Certificate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryIssuer queries the "issuer" edge of the Certificate entity.
func (_m *Certificate) QueryIssuer() *CertificateQuery {
	return NewCertificateClient(_m.config).QueryIssuer(_m)
}

// QueryChildren queries the "children" edge of the Certificate entity.
func (_m *Certificate) QueryChildren() *CertificateQuery {
	return NewCertificateClient(_m.config).QueryChildren(_m)
}

// Update returns a builder for updating this Certificate.
// Note that you need to call Certificate.Unwrap() before calling this method if this Certificate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Certificate) Update() *CertificateUpdateOne {
	return NewCertificateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Certificate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Certificate) Unwrap() *Certificate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Certificate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Certificate) String() string {
	var builder strings.Builder
	builder.WriteString("Certificate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("common_name=")
	builder.WriteString(_m.CommonName)
	builder.WriteString(", ")
	builder.WriteString("serial_number=")
	builder.WriteString(_m.SerialNumber)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("key_type=")
	builder.WriteString(_m.KeyType)
	builder.WriteString(", ")
	builder.WriteString("fingerprint=")
	builder.WriteString(_m.Fingerprint)
	builder.WriteString(", ")
	builder.WriteString("cert_path=")
	builder.WriteString(_m.CertPath)
	builder.WriteString(", ")
	builder.WriteString("key_path=")
	builder.WriteString(_m.KeyPath)
	builder.WriteString(", ")
	builder.WriteString("organization=")
	builder.WriteString(_m.Organization)
	builder.WriteString(", ")
	builder.WriteString("country=")
	builder.WriteString(_m.Country)
	builder.WriteString(", ")
	builder.WriteString("dns_names=")
	builder.WriteString(fmt.Sprintf("%v", _m.DNSNames))
	builder.WriteString(", ")
	builder.WriteString("ip_addresses=")
	builder.WriteString(fmt.Sprintf("%v", _m.IPAddresses))
	builder.WriteString(", ")
	builder.WriteString("is_ca=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsCa))
	builder.WriteByte(')')
	return builder.String()
}

// Certificates is a parsable slice of Certificate.
type Certificates []*Certificate
