// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/snowmerak/mtls/ent/certificate"
)

// CertificateCreate is the builder for creating a Certificate entity.
type CertificateCreate struct {
	config
	mutation *CertificateMutation
	hooks    []Hook
}

// SetCommonName sets the "common_name" field.
func (_c *CertificateCreate) SetCommonName(v string) *CertificateCreate {
	_c.mutation.SetCommonName(v)
	return _c
}

// SetSerialNumber sets the "serial_number" field.
func (_c *CertificateCreate) SetSerialNumber(v string) *CertificateCreate {
	_c.mutation.SetSerialNumber(v)
	return _c
}

// SetType sets the "type" field.
func (_c *CertificateCreate) SetType(v certificate.Type) *CertificateCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *CertificateCreate) SetStatus(v certificate.Status) *CertificateCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableStatus(v *certificate.Status) *CertificateCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CertificateCreate) SetCreatedAt(v time.Time) *CertificateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableCreatedAt(v *time.Time) *CertificateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *CertificateCreate) SetExpiresAt(v time.Time) *CertificateCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *CertificateCreate) SetRevokedAt(v time.Time) *CertificateCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableRevokedAt(v *time.Time) *CertificateCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetKeyType sets the "key_type" field.
func (_c *CertificateCreate) SetKeyType(v string) *CertificateCreate {
	_c.mutation.SetKeyType(v)
	return _c
}

// SetFingerprint sets the "fingerprint" field.
func (_c *CertificateCreate) SetFingerprint(v string) *CertificateCreate {
	_c.mutation.SetFingerprint(v)
	return _c
}

// SetCertPath sets the "cert_path" field.
func (_c *CertificateCreate) SetCertPath(v string) *CertificateCreate {
	_c.mutation.SetCertPath(v)
	return _c
}

// SetKeyPath sets the "key_path" field.
func (_c *CertificateCreate) SetKeyPath(v string) *CertificateCreate {
	_c.mutation.SetKeyPath(v)
	return _c
}

// SetOrganization sets the "organization" field.
func (_c *CertificateCreate) SetOrganization(v string) *CertificateCreate {
	_c.mutation.SetOrganization(v)
	return _c
}

// SetNillableOrganization sets the "organization" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableOrganization(v *string) *CertificateCreate {
	if v != nil {
		_c.SetOrganization(*v)
	}
	return _c
}

// SetCountry sets the "country" field.
func (_c *CertificateCreate) SetCountry(v string) *CertificateCreate {
	_c.mutation.SetCountry(v)
	return _c
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableCountry(v *string) *CertificateCreate {
	if v != nil {
		_c.SetCountry(*v)
	}
	return _c
}

// SetDNSNames sets the "dns_names" field.
func (_c *CertificateCreate) SetDNSNames(v []string) *CertificateCreate {
	_c.mutation.SetDNSNames(v)
	return _c
}

// SetIPAddresses sets the "ip_addresses" field.
func (_c *CertificateCreate) SetIPAddresses(v []string) *CertificateCreate {
	_c.mutation.SetIPAddresses(v)
	return _c
}

// SetIsCa sets the "is_ca" field.
func (_c *CertificateCreate) SetIsCa(v bool) *CertificateCreate {
	_c.mutation.SetIsCa(v)
	return _c
}

// SetNillableIsCa sets the "is_ca" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableIsCa(v *bool) *CertificateCreate {
	if v != nil {
		_c.SetIsCa(*v)
	}
	return _c
}

// SetIssuerID sets the "issuer" edge to the Certificate entity by ID.
func (_c *CertificateCreate) SetIssuerID(id int) *CertificateCreate {
	_c.mutation.SetIssuerID(id)
	return _c
}

// SetNillableIssuerID sets the "issuer" edge to the Certificate entity by ID if the given value is not nil.
func (_c *CertificateCreate) SetNillableIssuerID(id *int) *CertificateCreate {
	if id != nil {
		_c = _c.SetIssuerID(*id)
	}
	return _c
}

// SetIssuer sets the "issuer" edge to the Certificate entity.
func (_c *CertificateCreate) SetIssuer(v *Certificate) *CertificateCreate {
	return _c.SetIssuerID(v.ID)
}

// AddChildIDs adds the "children" edge to the Certificate entity by IDs.
func (_c *CertificateCreate) AddChildIDs(ids ...int) *CertificateCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the Certificate entity.
func (_c *CertificateCreate) AddChildren(v ...*Certificate) *CertificateCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// Mutation returns the CertificateMutation object of the builder.
func (_c *CertificateCreate) Mutation() *CertificateMutation {
	return _c.mutation
}

// Save creates the Certificate in the database.
func (_c *CertificateCreate) Save(ctx context.Context) (*Certificate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CertificateCreate) SaveX(ctx context.Context) *Certificate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CertificateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CertificateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CertificateCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := certificate.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := certificate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.IsCa(); !ok {
		v := certificate.DefaultIsCa
		_c.mutation.SetIsCa(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CertificateCreate) check() error {
	if _, ok := _c.mutation.CommonName(); !ok {
		return &ValidationError{Name: "common_name", err: errors.New(`ent: missing required field "Certificate.common_name"`)}
	}
	if _, ok := _c.mutation.SerialNumber(); !ok {
		return &ValidationError{Name: "serial_number", err: errors.New(`ent: missing required field "Certificate.serial_number"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Certificate.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := certificate.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Certificate.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Certificate.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := certificate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Certificate.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Certificate.created_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "Certificate.expires_at"`)}
	}
	if _, ok := _c.mutation.KeyType(); !ok {
		return &ValidationError{Name: "key_type", err: errors.New(`ent: missing required field "Certificate.key_type"`)}
	}
	if _, ok := _c.mutation.Fingerprint(); !ok {
		return &ValidationError{Name: "fingerprint", err: errors.New(`ent: missing required field "Certificate.fingerprint"`)}
	}
	if _, ok := _c.mutation.CertPath(); !ok {
		return &ValidationError{Name: "cert_path", err: errors.New(`ent: missing required field "Certificate.cert_path"`)}
	}
	if _, ok := _c.mutation.KeyPath(); !ok {
		return &ValidationError{Name: "key_path", err: errors.New(`ent: missing required field "Certificate.key_path"`)}
	}
	if _, ok := _c.mutation.IsCa(); !ok {
		return &ValidationError{Name: "is_ca", err: errors.New(`ent: missing required field "Certificate.is_ca"`)}
	}
	return nil
}

func (_c *CertificateCreate) sqlSave(ctx context.Context) (*Certificate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CertificateCreate) createSpec() (*Certificate, *sqlgraph.CreateSpec) {
	var (
		_node = &Certificate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(certificate.Table, sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CommonName(); ok {
		_spec.SetField(certificate.FieldCommonName, field.TypeString, value)
		_node.CommonName = value
	}
	if value, ok := _c.mutation.SerialNumber(); ok {
		_spec.SetField(certificate.FieldSerialNumber, field.TypeString, value)
		_node.SerialNumber = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(certificate.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(certificate.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(certificate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(certificate.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(certificate.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if value, ok := _c.mutation.KeyType(); ok {
		_spec.SetField(certificate.FieldKeyType, field.TypeString, value)
		_node.KeyType = value
	}
	if value, ok := _c.mutation.Fingerprint(); ok {
		_spec.SetField(certificate.FieldFingerprint, field.TypeString, value)
		_node.Fingerprint = value
	}
	if value, ok := _c.mutation.CertPath(); ok {
		_spec.SetField(certificate.FieldCertPath, field.TypeString, value)
		_node.CertPath = value
	}
	if value, ok := _c.mutation.KeyPath(); ok {
		_spec.SetField(certificate.FieldKeyPath, field.TypeString, value)
		_node.KeyPath = value
	}
	if value, ok := _c.mutation.Organization(); ok {
		_spec.SetField(certificate.FieldOrganization, field.TypeString, value)
		_node.Organization = value
	}
	if value, ok := _c.mutation.Country(); ok {
		_spec.SetField(certificate.FieldCountry, field.TypeString, value)
		_node.Country = value
	}
	if value, ok := _c.mutation.DNSNames(); ok {
		_spec.SetField(certificate.FieldDNSNames, field.TypeJSON, value)
		_node.DNSNames = value
	}
	if value, ok := _c.mutation.IPAddresses(); ok {
		_spec.SetField(certificate.FieldIPAddresses, field.TypeJSON, value)
		_node.IPAddresses = value
	}
	if value, ok := _c.mutation.IsCa(); ok {
		_spec.SetField(certificate.FieldIsCa, field.TypeBool, value)
		_node.IsCa = value
	}
	if nodes := _c.mutation.IssuerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   certificate.IssuerTable,
			Columns: []string{certificate.IssuerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.certificate_children = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   certificate.ChildrenTable,
			Columns: []string{certificate.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CertificateCreateBulk is the builder for creating many Certificate entities in bulk.
type CertificateCreateBulk struct {
	config
	err      error
	builders []*CertificateCreate
}

// Save creates the Certificate entities in the database.
func (_c *CertificateCreateBulk) Save(ctx context.Context) ([]*Certificate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Certificate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CertificateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CertificateCreateBulk) SaveX(ctx context.Context) []*Certificate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CertificateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CertificateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
