// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/snowmerak/mtls/ent/certificate"
	"github.com/snowmerak/mtls/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeCertificate = "Certificate"
)

// CertificateMutation represents an operation that mutates the Certificate nodes in the graph.
type CertificateMutation struct {
	config
	op                 Op
	typ                string
	id                 *int
	common_name        *string
	serial_number      *string
	_type              *certificate.Type
	status             *certificate.Status
	created_at         *time.Time
	expires_at         *time.Time
	revoked_at         *time.Time
	key_type           *string
	fingerprint        *string
	cert_path          *string
	key_path           *string
	organization       *string
	country            *string
	dns_names          *[]string
	appenddns_names    []string
	ip_addresses       *[]string
	appendip_addresses []string
	is_ca              *bool
	clearedFields      map[string]struct{}
	issuer             *int
	clearedissuer      bool
	children           map[int]struct{}
	removedchildren    map[int]struct{}
	clearedchildren    bool
	done               bool
	oldValue           func(context.Context) (*Certificate, error)
	predicates         []predicate.Certificate
}

var _ ent.Mutation = (*CertificateMutation)(nil)

// certificateOption allows management of the mutation configuration using functional options.
type certificateOption func(*CertificateMutation)

// newCertificateMutation creates new mutation for the Certificate entity.
func newCertificateMutation(c config, op Op, opts ...certificateOption) *CertificateMutation {
	m := &CertificateMutation{
		config:        c,
		op:            op,
		typ:           TypeCertificate,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withCertificateID sets the ID field of the mutation.
func withCertificateID(id int) certificateOption {
	return func(m *CertificateMutation) {
		var (
			err   error
			once  sync.Once
			value *Certificate
		)
		m.oldValue = func(ctx context.Context) (*Certificate, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Certificate.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withCertificate sets the old Certificate of the mutation.
func withCertificate(node *Certificate) certificateOption {
	return func(m *CertificateMutation) {
		m.oldValue = func(context.Context) (*Certificate, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m CertificateMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m CertificateMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *CertificateMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *CertificateMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Certificate.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCommonName sets the "common_name" field.
func (m *CertificateMutation) SetCommonName(s string) {
	m.common_name = &s
}

// CommonName returns the value of the "common_name" field in the mutation.
func (m *CertificateMutation) CommonName() (r string, exists bool) {
	v := m.common_name
	if v == nil {
		return
	}
	return *v, true
}

// OldCommonName returns the old "common_name" field's value of the Certificate entity.
// If the Certificate object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CertificateMutation) OldCommonName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCommonName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCommonName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCommonName: %w", err)
	}
	return oldValue.CommonName, nil
}

// ResetCommonName resets all changes to the "common_name" field.
func (m *CertificateMutation) ResetCommonName() {
	m.common_name = nil
}

// SetSerialNumber sets the "serial_number" field.
func (m *CertificateMutation) SetSerialNumber(s string) {
	m.serial_number = &s
}

// SerialNumber returns the value of the "serial_number" field in the mutation.
func (m *CertificateMutation) SerialNumber() (r string, exists bool) {
	v := m.serial_number
	if v == nil {
		return
	}
	return *v, true
}

// OldSerialNumber returns the old "serial_number" field's value of the Certificate entity.
// If the Certificate object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CertificateMutation) OldSerialNumber(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSerialNumber is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSerialNumber requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSerialNumber: %w", err)
	}
	return oldValue.SerialNumber, nil
}

// ResetSerialNumber resets all changes to the "serial_number" field.
func (m *CertificateMutation) ResetSerialNumber() {
	m.serial_number = nil
}

// SetType sets the "type" field.
func (m *CertificateMutation) SetType(c certificate.Type) {
	m._type = &c
}

// GetType returns the value of the "type" field in the mutation.
func (m *CertificateMutation) GetType() (r certificate.Type, exists bool) {
	v := m._type
	if v == nil {
		return
	}
	return *v, true
}

// OldType returns the old "type" field's value of the Certificate entity.
// If the Certificate object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CertificateMutation) OldType(ctx context.Context) (v certificate.Type, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldType: %w", err)
	}
	return oldValue.Type, nil
}

// ResetType resets all changes to the "type" field.
func (m *CertificateMutation) ResetType() {
	m._type = nil
}

// SetStatus sets the "status" field.
func (m *CertificateMutation) SetStatus(c certificate.Status) {
	m.status = &c
}

// Status returns the value of the "status" field in the mutation.
func (m *CertificateMutation) Status() (r certificate.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the Certificate entity.
// If the Certificate object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CertificateMutation) OldStatus(ctx context.Context) (v certificate.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *CertificateMutation) ResetStatus() {
	m.status = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *CertificateMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *CertificateMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Certificate entity.
// If the Certificate object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CertificateMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *CertificateMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetExpiresAt sets the "expires_at" field.
func (m *CertificateMutation) SetExpiresAt(t time.Time) {
	m.expires_at = &t
}

// ExpiresAt returns the value of the "expires_at" field in the mutation.
func (m *CertificateMutation) ExpiresAt() (r time.Time, exists bool) {
	v := m.expires_at
	if v == nil {
		return
	}
	return *v, true
}

// OldExpiresAt returns the old "expires_at" field's value of the Certificate entity.
// If the Certificate object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CertificateMutation) OldExpiresAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExpiresAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExpiresAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExpiresAt: %w", err)
	}
	return oldValue.ExpiresAt, nil
}

// ResetExpiresAt resets all changes to the "expires_at" field.
func (m *CertificateMutation) ResetExpiresAt() {
	m.expires_at = nil
}

// SetRevokedAt sets the "revoked_at" field.
func (m *CertificateMutation) SetRevokedAt(t time.Time) {
	m.revoked_at = &t
}

// RevokedAt returns the value of the "revoked_at" field in the mutation.
func (m *CertificateMutation) RevokedAt() (r time.Time, exists bool) {
	v := m.revoked_at
	if v == nil {
		return
	}
	return *v, true
}

// OldRevokedAt returns the old "revoked_at" field's value of the Certificate entity.
// If the Certificate object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CertificateMutation) OldRevokedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRevokedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRevokedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRevokedAt: %w", err)
	}
	return oldValue.RevokedAt, nil
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (m *CertificateMutation) ClearRevokedAt() {
	m.revoked_at = nil
	m.clearedFields[certificate.FieldRevokedAt] = struct{}{}
}

// RevokedAtCleared returns if the "revoked_at" field was cleared in this mutation.
func (m *CertificateMutation) RevokedAtCleared() bool {
	_, ok := m.clearedFields[certificate.FieldRevokedAt]
	return ok
}

// ResetRevokedAt resets all changes to the "revoked_at" field.
func (m *CertificateMutation) ResetRevokedAt() {
	m.revoked_at = nil
	delete(m.clearedFields, certificate.FieldRevokedAt)
}

// SetKeyType sets the "key_type" field.
func (m *CertificateMutation) SetKeyType(s string) {
	m.key_type = &s
}

// KeyType returns the value of the "key_type" field in the mutation.
func (m *CertificateMutation) KeyType() (r string, exists bool) {
	v := m.key_type
	if v == nil {
		return
	}
	return *v, true
}

// OldKeyType returns the old "key_type" field's value of the Certificate entity.
// If the Certificate object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CertificateMutation) OldKeyType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldKeyType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldKeyType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldKeyType: %w", err)
	}
	return oldValue.KeyType, nil
}

// ResetKeyType resets all changes to the "key_type" field.
func (m *CertificateMutation) ResetKeyType() {
	m.key_type = nil
}

// SetFingerprint sets the "fingerprint" field.
func (m *CertificateMutation) SetFingerprint(s string) {
	m.fingerprint = &s
}

// Fingerprint returns the value of the "fingerprint" field in the mutation.
func (m *CertificateMutation) Fingerprint() (r string, exists bool) {
	v := m.fingerprint
	if v == nil {
		return
	}
	return *v, true
}

// OldFingerprint returns the old "fingerprint" field's value of the Certificate entity.
// If the Certificate object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CertificateMutation) OldFingerprint(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFingerprint is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFingerprint requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFingerprint: %w", err)
	}
	return oldValue.Fingerprint, nil
}

// ResetFingerprint resets all changes to the "fingerprint" field.
func (m *CertificateMutation) ResetFingerprint() {
	m.fingerprint = nil
}

// SetCertPath sets the "cert_path" field.
func (m *CertificateMutation) SetCertPath(s string) {
	m.cert_path = &s
}

// CertPath returns the value of the "cert_path" field in the mutation.
func (m *CertificateMutation) CertPath() (r string, exists bool) {
	v := m.cert_path
	if v == nil {
		return
	}
	return *v, true
}

// OldCertPath returns the old "cert_path" field's value of the Certificate entity.
// If the Certificate object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CertificateMutation) OldCertPath(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCertPath is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCertPath requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCertPath: %w", err)
	}
	return oldValue.CertPath, nil
}

// ResetCertPath resets all changes to the "cert_path" field.
func (m *CertificateMutation) ResetCertPath() {
	m.cert_path = nil
}

// SetKeyPath sets the "key_path" field.
func (m *CertificateMutation) SetKeyPath(s string) {
	m.key_path = &s
}

// KeyPath returns the value of the "key_path" field in the mutation.
func (m *CertificateMutation) KeyPath() (r string, exists bool) {
	v := m.key_path
	if v == nil {
		return
	}
	return *v, true
}

// OldKeyPath returns the old "key_path" field's value of the Certificate entity.
// If the Certificate object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CertificateMutation) OldKeyPath(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldKeyPath is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldKeyPath requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldKeyPath: %w", err)
	}
	return oldValue.KeyPath, nil
}

// ResetKeyPath resets all changes to the "key_path" field.
func (m *CertificateMutation) ResetKeyPath() {
	m.key_path = nil
}

// SetOrganization sets the "organization" field.
func (m *CertificateMutation) SetOrganization(s string) {
	m.organization = &s
}

// Organization returns the value of the "organization" field in the mutation.
func (m *CertificateMutation) Organization() (r string, exists bool) {
	v := m.organization
	if v == nil {
		return
	}
	return *v, true
}

// OldOrganization returns the old "organization" field's value of the Certificate entity.
// If the Certificate object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CertificateMutation) OldOrganization(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOrganization is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOrganization requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOrganization: %w", err)
	}
	return oldValue.Organization, nil
}

// ClearOrganization clears the value of the "organization" field.
func (m *CertificateMutation) ClearOrganization() {
	m.organization = nil
	m.clearedFields[certificate.FieldOrganization] = struct{}{}
}

// OrganizationCleared returns if the "organization" field was cleared in this mutation.
func (m *CertificateMutation) OrganizationCleared() bool {
	_, ok := m.clearedFields[certificate.FieldOrganization]
	return ok
}

// ResetOrganization resets all changes to the "organization" field.
func (m *CertificateMutation) ResetOrganization() {
	m.organization = nil
	delete(m.clearedFields, certificate.FieldOrganization)
}

// SetCountry sets the "country" field.
func (m *CertificateMutation) SetCountry(s string) {
	m.country = &s
}

// Country returns the value of the "country" field in the mutation.
func (m *CertificateMutation) Country() (r string, exists bool) {
	v := m.country
	if v == nil {
		return
	}
	return *v, true
}

// OldCountry returns the old "country" field's value of the Certificate entity.
// If the Certificate object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CertificateMutation) OldCountry(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCountry is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCountry requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCountry: %w", err)
	}
	return oldValue.Country, nil
}

// ClearCountry clears the value of the "country" field.
func (m *CertificateMutation) ClearCountry() {
	m.country = nil
	m.clearedFields[certificate.FieldCountry] = struct{}{}
}

// CountryCleared returns if the "country" field was cleared in this mutation.
func (m *CertificateMutation) CountryCleared() bool {
	_, ok := m.clearedFields[certificate.FieldCountry]
	return ok
}

// ResetCountry resets all changes to the "country" field.
func (m *CertificateMutation) ResetCountry() {
	m.country = nil
	delete(m.clearedFields, certificate.FieldCountry)
}

// SetDNSNames sets the "dns_names" field.
func (m *CertificateMutation) SetDNSNames(s []string) {
	m.dns_names = &s
	m.appenddns_names = nil
}

// DNSNames returns the value of the "dns_names" field in the mutation.
func (m *CertificateMutation) DNSNames() (r []string, exists bool) {
	v := m.dns_names
	if v == nil {
		return
	}
	return *v, true
}

// OldDNSNames returns the old "dns_names" field's value of the Certificate entity.
// If the Certificate object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CertificateMutation) OldDNSNames(ctx context.Context) (v []string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDNSNames is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDNSNames requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDNSNames: %w", err)
	}
	return oldValue.DNSNames, nil
}

// AppendDNSNames adds s to the "dns_names" field.
func (m *CertificateMutation) AppendDNSNames(s []string) {
	m.appenddns_names = append(m.appenddns_names, s...)
}

// AppendedDNSNames returns the list of values that were appended to the "dns_names" field in this mutation.
func (m *CertificateMutation) AppendedDNSNames() ([]string, bool) {
	if len(m.appenddns_names) == 0 {
		return nil, false
	}
	return m.appenddns_names, true
}

// ClearDNSNames clears the value of the "dns_names" field.
func (m *CertificateMutation) ClearDNSNames() {
	m.dns_names = nil
	m.appenddns_names = nil
	m.clearedFields[certificate.FieldDNSNames] = struct{}{}
}

// DNSNamesCleared returns if the "dns_names" field was cleared in this mutation.
func (m *CertificateMutation) DNSNamesCleared() bool {
	_, ok := m.clearedFields[certificate.FieldDNSNames]
	return ok
}

// ResetDNSNames resets all changes to the "dns_names" field.
func (m *CertificateMutation) ResetDNSNames() {
	m.dns_names = nil
	m.appenddns_names = nil
	delete(m.clearedFields, certificate.FieldDNSNames)
}

// SetIPAddresses sets the "ip_addresses" field.
func (m *CertificateMutation) SetIPAddresses(s []string) {
	m.ip_addresses = &s
	m.appendip_addresses = nil
}

// IPAddresses returns the value of the "ip_addresses" field in the mutation.
func (m *CertificateMutation) IPAddresses() (r []string, exists bool) {
	v := m.ip_addresses
	if v == nil {
		return
	}
	return *v, true
}

// OldIPAddresses returns the old "ip_addresses" field's value of the Certificate entity.
// If the Certificate object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CertificateMutation) OldIPAddresses(ctx context.Context) (v []string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIPAddresses is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIPAddresses requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIPAddresses: %w", err)
	}
	return oldValue.IPAddresses, nil
}

// AppendIPAddresses adds s to the "ip_addresses" field.
func (m *CertificateMutation) AppendIPAddresses(s []string) {
	m.appendip_addresses = append(m.appendip_addresses, s...)
}

// AppendedIPAddresses returns the list of values that were appended to the "ip_addresses" field in this mutation.
func (m *CertificateMutation) AppendedIPAddresses() ([]string, bool) {
	if len(m.appendip_addresses) == 0 {
		return nil, false
	}
	return m.appendip_addresses, true
}

// ClearIPAddresses clears the value of the "ip_addresses" field.
func (m *CertificateMutation) ClearIPAddresses() {
	m.ip_addresses = nil
	m.appendip_addresses = nil
	m.clearedFields[certificate.FieldIPAddresses] = struct{}{}
}

// IPAddressesCleared returns if the "ip_addresses" field was cleared in this mutation.
func (m *CertificateMutation) IPAddressesCleared() bool {
	_, ok := m.clearedFields[certificate.FieldIPAddresses]
	return ok
}

// ResetIPAddresses resets all changes to the "ip_addresses" field.
func (m *CertificateMutation) ResetIPAddresses() {
	m.ip_addresses = nil
	m.appendip_addresses = nil
	delete(m.clearedFields, certificate.FieldIPAddresses)
}

// SetIsCa sets the "is_ca" field.
func (m *CertificateMutation) SetIsCa(b bool) {
	m.is_ca = &b
}

// IsCa returns the value of the "is_ca" field in the mutation.
func (m *CertificateMutation) IsCa() (r bool, exists bool) {
	v := m.is_ca
	if v == nil {
		return
	}
	return *v, true
}

// OldIsCa returns the old "is_ca" field's value of the Certificate entity.
// If the Certificate object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CertificateMutation) OldIsCa(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsCa is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsCa requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsCa: %w", err)
	}
	return oldValue.IsCa, nil
}

// ResetIsCa resets all changes to the "is_ca" field.
func (m *CertificateMutation) ResetIsCa() {
	m.is_ca = nil
}

// SetIssuerID sets the "issuer" edge to the Certificate entity by id.
func (m *CertificateMutation) SetIssuerID(id int) {
	m.issuer = &id
}

// ClearIssuer clears the "issuer" edge to the Certificate entity.
func (m *CertificateMutation) ClearIssuer() {
	m.clearedissuer = true
}

// IssuerCleared reports if the "issuer" edge to the Certificate entity was cleared.
func (m *CertificateMutation) IssuerCleared() bool {
	return m.clearedissuer
}

// IssuerID returns the "issuer" edge ID in the mutation.
func (m *CertificateMutation) IssuerID() (id int, exists bool) {
	if m.issuer != nil {
		return *m.issuer, true
	}
	return
}

// IssuerIDs returns the "issuer" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// IssuerID instead. It exists only for internal usage by the builders.
func (m *CertificateMutation) IssuerIDs() (ids []int) {
	if id := m.issuer; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetIssuer resets all changes to the "issuer" edge.
func (m *CertificateMutation) ResetIssuer() {
	m.issuer = nil
	m.clearedissuer = false
}

// AddChildIDs adds the "children" edge to the Certificate entity by ids.
func (m *CertificateMutation) AddChildIDs(ids ...int) {
	if m.children == nil {
		m.children = make(map[int]struct{})
	}
	for i := range ids {
		m.children[ids[i]] = struct{}{}
	}
}

// ClearChildren clears the "children" edge to the Certificate entity.
func (m *CertificateMutation) ClearChildren() {
	m.clearedchildren = true
}

// ChildrenCleared reports if the "children" edge to the Certificate entity was cleared.
func (m *CertificateMutation) ChildrenCleared() bool {
	return m.clearedchildren
}

// RemoveChildIDs removes the "children" edge to the Certificate entity by IDs.
func (m *CertificateMutation) RemoveChildIDs(ids ...int) {
	if m.removedchildren == nil {
		m.removedchildren = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.children, ids[i])
		m.removedchildren[ids[i]] = struct{}{}
	}
}

// RemovedChildren returns the removed IDs of the "children" edge to the Certificate entity.
func (m *CertificateMutation) RemovedChildrenIDs() (ids []int) {
	for id := range m.removedchildren {
		ids = append(ids, id)
	}
	return
}

// ChildrenIDs returns the "children" edge IDs in the mutation.
func (m *CertificateMutation) ChildrenIDs() (ids []int) {
	for id := range m.children {
		ids = append(ids, id)
	}
	return
}

// ResetChildren resets all changes to the "children" edge.
func (m *CertificateMutation) ResetChildren() {
	m.children = nil
	m.clearedchildren = false
	m.removedchildren = nil
}

// Where appends a list predicates to the CertificateMutation builder.
func (m *CertificateMutation) Where(ps ...predicate.Certificate) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the CertificateMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *CertificateMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Certificate, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *CertificateMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *CertificateMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Certificate).
func (m *CertificateMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *CertificateMutation) Fields() []string {
	fields := make([]string, 0, 16)
	if m.common_name != nil {
		fields = append(fields, certificate.FieldCommonName)
	}
	if m.serial_number != nil {
		fields = append(fields, certificate.FieldSerialNumber)
	}
	if m._type != nil {
		fields = append(fields, certificate.FieldType)
	}
	if m.status != nil {
		fields = append(fields, certificate.FieldStatus)
	}
	if m.created_at != nil {
		fields = append(fields, certificate.FieldCreatedAt)
	}
	if m.expires_at != nil {
		fields = append(fields, certificate.FieldExpiresAt)
	}
	if m.revoked_at != nil {
		fields = append(fields, certificate.FieldRevokedAt)
	}
	if m.key_type != nil {
		fields = append(fields, certificate.FieldKeyType)
	}
	if m.fingerprint != nil {
		fields = append(fields, certificate.FieldFingerprint)
	}
	if m.cert_path != nil {
		fields = append(fields, certificate.FieldCertPath)
	}
	if m.key_path != nil {
		fields = append(fields, certificate.FieldKeyPath)
	}
	if m.organization != nil {
		fields = append(fields, certificate.FieldOrganization)
	}
	if m.country != nil {
		fields = append(fields, certificate.FieldCountry)
	}
	if m.dns_names != nil {
		fields = append(fields, certificate.FieldDNSNames)
	}
	if m.ip_addresses != nil {
		fields = append(fields, certificate.FieldIPAddresses)
	}
	if m.is_ca != nil {
		fields = append(fields, certificate.FieldIsCa)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *CertificateMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case certificate.FieldCommonName:
		return m.CommonName()
	case certificate.FieldSerialNumber:
		return m.SerialNumber()
	case certificate.FieldType:
		return m.GetType()
	case certificate.FieldStatus:
		return m.Status()
	case certificate.FieldCreatedAt:
		return m.CreatedAt()
	case certificate.FieldExpiresAt:
		return m.ExpiresAt()
	case certificate.FieldRevokedAt:
		return m.RevokedAt()
	case certificate.FieldKeyType:
		return m.KeyType()
	case certificate.FieldFingerprint:
		return m.Fingerprint()
	case certificate.FieldCertPath:
		return m.CertPath()
	case certificate.FieldKeyPath:
		return m.KeyPath()
	case certificate.FieldOrganization:
		return m.Organization()
	case certificate.FieldCountry:
		return m.Country()
	case certificate.FieldDNSNames:
		return m.DNSNames()
	case certificate.FieldIPAddresses:
		return m.IPAddresses()
	case certificate.FieldIsCa:
		return m.IsCa()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *CertificateMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case certificate.FieldCommonName:
		return m.OldCommonName(ctx)
	case certificate.FieldSerialNumber:
		return m.OldSerialNumber(ctx)
	case certificate.FieldType:
		return m.OldType(ctx)
	case certificate.FieldStatus:
		return m.OldStatus(ctx)
	case certificate.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case certificate.FieldExpiresAt:
		return m.OldExpiresAt(ctx)
	case certificate.FieldRevokedAt:
		return m.OldRevokedAt(ctx)
	case certificate.FieldKeyType:
		return m.OldKeyType(ctx)
	case certificate.FieldFingerprint:
		return m.OldFingerprint(ctx)
	case certificate.FieldCertPath:
		return m.OldCertPath(ctx)
	case certificate.FieldKeyPath:
		return m.OldKeyPath(ctx)
	case certificate.FieldOrganization:
		return m.OldOrganization(ctx)
	case certificate.FieldCountry:
		return m.OldCountry(ctx)
	case certificate.FieldDNSNames:
		return m.OldDNSNames(ctx)
	case certificate.FieldIPAddresses:
		return m.OldIPAddresses(ctx)
	case certificate.FieldIsCa:
		return m.OldIsCa(ctx)
	}
	return nil, fmt.Errorf("unknown Certificate field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CertificateMutation) SetField(name string, value ent.Value) error {
	switch name {
	case certificate.FieldCommonName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCommonName(v)
		return nil
	case certificate.FieldSerialNumber:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSerialNumber(v)
		return nil
	case certificate.FieldType:
		v, ok := value.(certificate.Type)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetType(v)
		return nil
	case certificate.FieldStatus:
		v, ok := value.(certificate.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case certificate.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case certificate.FieldExpiresAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExpiresAt(v)
		return nil
	case certificate.FieldRevokedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRevokedAt(v)
		return nil
	case certificate.FieldKeyType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetKeyType(v)
		return nil
	case certificate.FieldFingerprint:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFingerprint(v)
		return nil
	case certificate.FieldCertPath:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCertPath(v)
		return nil
	case certificate.FieldKeyPath:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetKeyPath(v)
		return nil
	case certificate.FieldOrganization:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOrganization(v)
		return nil
	case certificate.FieldCountry:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCountry(v)
		return nil
	case certificate.FieldDNSNames:
		v, ok := value.([]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDNSNames(v)
		return nil
	case certificate.FieldIPAddresses:
		v, ok := value.([]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIPAddresses(v)
		return nil
	case certificate.FieldIsCa:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsCa(v)
		return nil
	}
	return fmt.Errorf("unknown Certificate field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *CertificateMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *CertificateMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CertificateMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Certificate numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *CertificateMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(certificate.FieldRevokedAt) {
		fields = append(fields, certificate.FieldRevokedAt)
	}
	if m.FieldCleared(certificate.FieldOrganization) {
		fields = append(fields, certificate.FieldOrganization)
	}
	if m.FieldCleared(certificate.FieldCountry) {
		fields = append(fields, certificate.FieldCountry)
	}
	if m.FieldCleared(certificate.FieldDNSNames) {
		fields = append(fields, certificate.FieldDNSNames)
	}
	if m.FieldCleared(certificate.FieldIPAddresses) {
		fields = append(fields, certificate.FieldIPAddresses)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *CertificateMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *CertificateMutation) ClearField(name string) error {
	switch name {
	case certificate.FieldRevokedAt:
		m.ClearRevokedAt()
		return nil
	case certificate.FieldOrganization:
		m.ClearOrganization()
		return nil
	case certificate.FieldCountry:
		m.ClearCountry()
		return nil
	case certificate.FieldDNSNames:
		m.ClearDNSNames()
		return nil
	case certificate.FieldIPAddresses:
		m.ClearIPAddresses()
		return nil
	}
	return fmt.Errorf("unknown Certificate nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *CertificateMutation) ResetField(name string) error {
	switch name {
	case certificate.FieldCommonName:
		m.ResetCommonName()
		return nil
	case certificate.FieldSerialNumber:
		m.ResetSerialNumber()
		return nil
	case certificate.FieldType:
		m.ResetType()
		return nil
	case certificate.FieldStatus:
		m.ResetStatus()
		return nil
	case certificate.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case certificate.FieldExpiresAt:
		m.ResetExpiresAt()
		return nil
	case certificate.FieldRevokedAt:
		m.ResetRevokedAt()
		return nil
	case certificate.FieldKeyType:
		m.ResetKeyType()
		return nil
	case certificate.FieldFingerprint:
		m.ResetFingerprint()
		return nil
	case certificate.FieldCertPath:
		m.ResetCertPath()
		return nil
	case certificate.FieldKeyPath:
		m.ResetKeyPath()
		return nil
	case certificate.FieldOrganization:
		m.ResetOrganization()
		return nil
	case certificate.FieldCountry:
		m.ResetCountry()
		return nil
	case certificate.FieldDNSNames:
		m.ResetDNSNames()
		return nil
	case certificate.FieldIPAddresses:
		m.ResetIPAddresses()
		return nil
	case certificate.FieldIsCa:
		m.ResetIsCa()
		return nil
	}
	return fmt.Errorf("unknown Certificate field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *CertificateMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.issuer != nil {
		edges = append(edges, certificate.EdgeIssuer)
	}
	if m.children != nil {
		edges = append(edges, certificate.EdgeChildren)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *CertificateMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case certificate.EdgeIssuer:
		if id := m.issuer; id != nil {
			return []ent.Value{*id}
		}
	case certificate.EdgeChildren:
		ids := make([]ent.Value, 0, len(m.children))
		for id := range m.children {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *CertificateMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedchildren != nil {
		edges = append(edges, certificate.EdgeChildren)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *CertificateMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case certificate.EdgeChildren:
		ids := make([]ent.Value, 0, len(m.removedchildren))
		for id := range m.removedchildren {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *CertificateMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedissuer {
		edges = append(edges, certificate.EdgeIssuer)
	}
	if m.clearedchildren {
		edges = append(edges, certificate.EdgeChildren)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *CertificateMutation) EdgeCleared(name string) bool {
	switch name {
	case certificate.EdgeIssuer:
		return m.clearedissuer
	case certificate.EdgeChildren:
		return m.clearedchildren
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *CertificateMutation) ClearEdge(name string) error {
	switch name {
	case certificate.EdgeIssuer:
		m.ClearIssuer()
		return nil
	}
	return fmt.Errorf("unknown Certificate unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *CertificateMutation) ResetEdge(name string) error {
	switch name {
	case certificate.EdgeIssuer:
		m.ResetIssuer()
		return nil
	case certificate.EdgeChildren:
		m.ResetChildren()
		return nil
	}
	return fmt.Errorf("unknown Certificate edge %s", name)
}
