// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/snowmerak/mtls/ent/certificate"
	"github.com/snowmerak/mtls/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	certificateFields := schema.Certificate{}.Fields()
	_ = certificateFields
	// certificateDescCreatedAt is the schema descriptor for created_at field.
	certificateDescCreatedAt := certificateFields[4].Descriptor()
	// certificate.DefaultCreatedAt holds the default value on creation for the created_at field.
	certificate.DefaultCreatedAt = certificateDescCreatedAt.Default.(func() time.Time)
	// certificateDescIsCa is the schema descriptor for is_ca field.
	certificateDescIsCa := certificateFields[15].Descriptor()
	// certificate.DefaultIsCa holds the default value on creation for the is_ca field.
	certificate.DefaultIsCa = certificateDescIsCa.Default.(bool)
}
